spring:
  cloud:
    function:
      definition: ordenEventoProduce;pagoProcesador;inventarioProcesador;envioProcesador
    stream:
      default:
        producer:
          useNativeEncoding: true
      bindings:
        ordenEventoProduce-out-0:
          destination: orden-eventos
        pagoProcesador-in-0:
          destination: pago-eventos
          group: orden-servicio-grupo
        inventarioProcesador-in-0:
          destination: inventario-eventos
          group: orden-servicio-grupo
      kafka:
        binder:
          consumer-properties:
            "value.deserializer": "org.springframework.kafka.support.serializer.JsonDeserializer"
            "key.deserializer": "org.apache.kafka.common.serialization.StringDeserializer"
            "auto.offset.reset": "earliest"
            "spring.json.trusted.packages": "com.misaico.events.*"
          producer-properties:
            "value.serializer": "org.springframework.kafka.support.serializer.JsonSerializer"
            "key.serializer": "org.apache.kafka.common.serialization.StringSerializer"
